# Generated by Django 3.1.5 on 2021-01-30 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210130_1210'),
        ('post', '0002_auto_20210129_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no',
            new_name='id',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post.post')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user.user')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
