# Generated by Django 3.1.5 on 2021-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='user_id', max_length=30)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('age', models.IntegerField(db_column='age')),
            ],
        ),
    ]
