# Generated by Django 3.1.5 on 2021-01-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='no',
            new_name='id',
        ),
    ]
